version: "2"

services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - "php-laravel:php"
    volumes_from:
      - "data"

  php-laravel:
    build:
      context: ../
      dockerfile: dockerfiles/laravel/Dockerfile
    volumes_from:
      - "data"

  data:
    image: tianon/true
    volumes:
      - "../../:/app"
      - "../config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../config/php/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini"
